### ISSUE TITLE
Consider adding a feature for showing scriptableobjects inline

### ISSUE THREAD

**Issue by IceSentry** [bitcake/bitstrap#12]
This thread explains exactly what I'm looking for

https://forum.unity.com/threads/editor-tool-better-scriptableobject-inspector-editing.484393/

It seems to be the kind of feature your package could have.

**Comment by vamolessa** [comment]
That'd be a nice addition!

Currently, we've been using this solution: https://gist.github.com/tomkail/ba4136e6aa990f4dc94e0d39ec6a058c

I'm thinking of doing something similar but bind the drawer to an Attribute so one could choose when to draw the ScriptableObject inline.

**Comment by Lawendt** [comment]
I did it on [Lawendts Unity Utilities](https://github.com/Lawendt/LawendtUnityUtilities).
I extended the drawer to have just the create button and created an attribute to display the SO fields (as you suggested). 

If you want I can open a PR with this!

**Comment by vamolessa** [comment]
Feel free to :)
I forgot to add that, in fact, we use your version (empty SO fix) of that script link I posted ahhahaa

**Comment by Lawendt** [comment]
Opened #13 with requested feature!

**Comment by vamolessa** [comment]
It's now merged! Thanks!
