### ISSUE TITLE
UPM support?

### ISSUE THREAD

**Issue by andybak** [bitcake/bitstrap#24]
It would be fantastic to install this via the Package Manager's git support. Happy to do a pull request if you're interested.

**Comment by vamolessa** [comment]
It would be awesome for sure!
We would very much welcome a PR :)
Thanks!

**Comment by vamolessa** [comment]
closing this since you can now install BitStrap through UPM with git

**Comment by andybak** [comment]
James gave me this track as a stop gap and I rather like how it fits.
https://drive.google.com/file/d/1Q9wdEpBTz7mXHZnKdn4Ivwk0riLkvPve/view?usp=sharing

I wondered if you'd consider a collaboration where you both supply stems
that can be combined?

I don't mind if you'd prefer to work on your own thing.
