### ISSUE TITLE
TweenShader not working on Sprite Renderer

### ISSUE THREAD

**Issue by Lawendt** [bitcake/bitstrap#3]
Was trying to use `TweenShader` to animate the material on a spriteRenderer and it turns out that it doesn't work as expected.

Before executing the tween:
![image](https://user-images.githubusercontent.com/13232242/39629470-b39cdc6c-4f82-11e8-9bae-233704d96f8e.png)

After executing:
![image](https://user-images.githubusercontent.com/13232242/39629494-c6c26f46-4f82-11e8-8515-745d042ff990.png)

The tween on the propriety work as expected, but the Sprite isn't rendered. 
With a little research I found out the problem mentioned on this [post](https://answers.unity.com/questions/1220153/sprite-with-materialpropertyblock-not-updating-unt.html). The way they fixed is pretty simple, but I was thinking on a more broad fix: setting all proprieties that are not being defined by the user as the "default" value.

**Comment by Lawendt** [comment]
Adding this line `targetRenderer.GetPropertyBlock(propertyBlock);` after clearing the `propertyBlock` seems to fix the problem.
But, adding it to the init method like this:
```			
if( propertyBlock == null )
{
   propertyBlock = new MaterialPropertyBlock();
   duration.onTimer.UnregisterAll();
   duration.onTimer.Register( OnTimer );
   targetRenderer.GetPropertyBlock(propertyBlock);
}
```

and **not** clearing at each sample fix it as well.

Would like to hear what you guys think is the best.

**Comment by vamolessa** [comment]
Was fixed with the PR. Will close.
